SRC += potyt.c

LINK_TIME_OPTIMIZATION_ENABLE = yes

BOOTMAGIC_ENABLE = full

BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = yes
SLEEP_LED_ENABLE = no
UNICODE_ENABLE = no
SWAP_HANDS_ENABLE = no
UNICODE_ENABLE = no
AUTO_SHIFT_ENABLE = yes
LEADER_ENABLE = yes
KEY_LOCK_ENABLE = yes
TAP_DANCE_ENABLE = yes
